import { ATTACKER, MIDFIELDER, DEFENDER, GOALKEEPER, POINT_GUARD, POWER_FORWARD, CENTER, SHOOTING_GUARD, SMALL_FORWARD } from './constants';

export const football = [ATTACKER, MIDFIELDER, DEFENDER, GOALKEEPER];
export const basketball = [POINT_GUARD, SHOOTING_GUARD, SMALL_FORWARD, POWER_FORWARD, CENTER];
