export const SEARCH_MATCH_BEGIN = 'SEARCH_MATCH_BEGIN';
export const SEARCH_MATCH_SUCCESS = 'SEARCH_MATCH_SUCCESS';
export const SEARCH_MATCH_FAILURE = 'SEARCH_MATCH_FAILURE';
export const RESET_SEARCH_MATCH_STATE = 'RESET_SEARCH_MATCH_STATE';
