export const SET_AVAILABLE_SPORTS = 'SET_AVAILABLE_SPORTS';
export const SET_UNAVAILABLE_SPORTS = 'SET_UNAVAILABLE_SPORTS';
export const ADD_AVAILABLE_SPORT = 'ADD_AVAILABLE_SPORT';
export const REMOVE_AVAILABLE_SPORT = 'REMOVE_AVAILABLE_SPORT';
export const ADD_UNAVAILABLE_SPORT = 'ADD_UNAVAILABLE_SPORT';
export const REMOVE_UNAVAILABLE_SPORT = 'REMOVE_UNAVAILABLE_SPORT';